services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=backend-db
      - DB_PORT=3306
      - DB_USER=fintrack_user
      - DB_PASSWORD=fintrack_pass
      - DB_DATABASE=fintrack
    depends_on:
      - backend-db

  backend-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fintrack
      MYSQL_USER: fintrack_user
      MYSQL_PASSWORD: fintrack_pass
    ports:
      - "3308:3306"

